export const AGREGAR_PACIENTE = 'AGREGAR_PACIENTE';
export const LISTAR_PACIENTE = 'LISTAR_PACIENTE';
export const EDITAR_PACIENTE = 'EDITAR_PACIENTE';
export const ELIMINAR_PACIENTE = 'ELIMINAR_PACIENTE';
export const PACIENTE_ACTUAL = 'PACIENTE_ACTUAL';
export const PACIENTE_NULL = 'PACIENTE_NULL';

export const LISTAR_PERSONA = 'LISTAR_PERSONAL';
export const EDITAR_PERSONAL = 'EDITAR_PERSONAL';
export const ELIMINAR_PERSONA = 'ELIMINAR_PERSONAL';
export const PERSONAL_ACTUAL = 'PERSONAL_ACTUAL';
export const AGREGAR_PERSONAL = 'AGREGAR_PERSONAL';
export const PERSONA_NULL = 'PERSONA_NULL';

export const CREAR_CITA = 'CREAR_CITA';
export const ASIGNAR_CITA = 'ASIGNAR_CITA';
export const LISTAR_CITA = 'LISTAR_CITA';
export const EDITAR_CITA = 'EDITAR_CITA';
export const ELIMINAR_CITA = 'ELIMINAR_CITA';
export const FILTRAR_CITAS = 'FILTRAR_CITAS';
export const ADQUIRIR_CITA = 'ADQUIRIR_CITA';
export const CITA_ACTUAL = 'CITA_ACTUAL';
export const CITA_NULL = 'CITA_NULL';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const LOGIN_EXITOSO= 'LOGIN_EXITOSO';
export const LOGIN_ERROR= 'LOGIN_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const CERRAR_SESION = 'CERRAR_SESION';

export const CREAR_FACTURA = 'CREAR_FACTURA';
export const LISTAR_FACTURA = 'LISTAR_FACTURA';

export const MOSTRAR_ALERTA= 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA= 'OCULTAR_ALERTA';