export const AGREGAR_PACIENTE = 'AGREGAR_PACIENTE';
export const LISTAR_PACIENTE = 'LISTAR_PACIENTE';
export const EDITAR_PACIENTE = 'EDITAR_PACIENTE';
export const ELIMINAR_PACIENTE = 'ELIMINAR_PACIENTE';
export const PACIENTE_ACTUAL = 'PACIENTE_ACTUAL';

export const LISTAR_PERSONA = 'LISTAR_PERSONAL';
export const EDITAR_PERSONA = 'EDITAR_PERSONAL';
export const ELIMINAR_PERSONA = 'ELIMINAR_PERSONAL';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const LOGIN_EXITOSO= 'LOGIN_EXITOSO';
export const LOGIN_ERROR= 'LOGIN_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const CERRAR_SESION = 'CERRAR_SESION';

export const MOSTRAR_ALERTA= 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA= 'OCULTAR_ALERTA';