export const LISTAR_PACIENTE = 'LISTAR_PACIENTE';
export const EDITAR_PACIENTE = 'EDITAR_PACIENTE';
export const ELIMINAR_PACIENTE = 'ELIMINAR_PACIENTE';

export const LISTAR_PERSONA = 'LISTAR_PERSONAL';
export const EDITAR_PERSONA = 'EDITAR_PERSONAL';
export const ELIMINAR_PERSONA = 'ELIMINAR_PERSONAL';